export enum ClientMessages {
  JOIN_ROOM = "JOIN_ROOM",
  NEW_SHADOW = "NEW_SHADOW",
  LINES_DESTROYED = "LINES_DESTROYED",
  PLAYER_GAME_OVER = "PLAYER_GAME_OVER",
  START_GAME = "START_GAME",
}

export enum ServerMessages {
  ROOM_INFO = "ROOM_INFO",
  GAME_STATUS = "GAME_STATUS",
  LEADER_NAME = "LEADER_NAME",
  SEND_OPPONENT = "SEND_OPPONENT",
  SEED = "SEED",
  OPPONENTS_SHADOWS = "OPPONENTS_SHADOWS",
  LINES_TO_BLOCK = "LINES_TO_BLOCK",
}
