export enum Messages {
  ROOM_LIST = "ROOM_LIST",
  ROOM_INFO = "ROOM_INFO",
  JOIN_ROOM = "JOIN_ROOM",
  GET_PIECE = "GET_PIECE",
  NEW_SHADOW = "NEW_SHADOW",
  START_GAME = "START_GAME",
  WAITING_ROOM = "WAITING_ROOM",
  SEND_OPPONENT = "SEND_OPPONENT",
  LINES_DESTROYED = "LINES_DESTROYED",
  NEW_NAME_PLAYER = "NEW_NAME_PLAYER",
  PLAYER_GAME_OVER = "PLAYER_GAME_OVER",
  TOGGLE_ACCELERATION = "TOGGLE_ACCELERATION",
}

export default Messages;
