export enum Messages {
  GET_PIECE = "GET_PIECE",
  JOIN_ROOM = "JOIN_ROOM",
  ROOM_LIST = "ROOM_LIST",
  ROOM_INFO = "ROOM_INFO",
  NEW_SHADOW = "NEW_SHADOW",
  START_GAME = "START_GAME",
  WAITING_ROOM = "WAITING_ROOM",
  SET_ALL_ALIVE = "SET_ALL_ALIVE",
  SEND_OPPONENT = "SEND_OPPONENT",
  NEW_PLAYER_NAME = "NEW_PLAYER_NAME",
  ROOM_DISCONNECT = "ROOM_DISCONNECT",
  LINES_DESTROYED = "LINES_DESTROYED",
  DELETE_OPPONENT = "DELETE_OPPONENT",
  PLAYER_GAME_OVER = "PLAYER_GAME_OVER",
  TOGGLE_ACCELERATION = "TOGGLE_ACCELERATION",
}

export enum PlayerStatus {
  WAITING = -1,
  DEAD,
  ALIVE,
}

export default PlayerStatus;
